# Generated by Django 2.0 on 2017-12-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gist',
            name='commentary',
            field=models.CharField(default='', max_length=300),
        ),
    ]
