# Generated by Django 2.0 on 2017-12-20 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygist', '0002_auto_20171220_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='gist',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
