# Generated by Django 2.0 on 2017-12-20 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygist', '0003_gist_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='gist',
            name='creator',
            field=models.CharField(default='', max_length=50),
        ),
    ]
