# Generated by Django 2.0 on 2017-12-21 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mygist', '0004_gist_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gist',
            name='title',
        ),
    ]
