# Generated by Django 2.0 on 2017-12-21 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygist', '0005_remove_gist_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='gist',
            name='category',
            field=models.CharField(choices=[('Suite', 'Suite'), ('Sort', 'Sort'), ('Util', 'Util'), ('None', 'None')], default='None', max_length=10),
        ),
    ]
