# Generated by Django 2.0 on 2017-12-21 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygist', '0006_gist_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gist',
            name='id',
        ),
        migrations.AlterField(
            model_name='gist',
            name='gid',
            field=models.SlugField(primary_key=True, serialize=False),
        ),
    ]
